site_name: MineStamp Docs # TODO Change this to your site name
theme:
  name: material
  language: ja
  logo: null
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary : green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary : green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
plugins:
  - search:
      lang: ja
repo_url: https://github.com/Nlkomaru/EmojiStamp # TODO Change this to your site name
repo_name: MineStamp # TODO Change this to your site name
copyright: No Rights Reserved(CC00).  Written by Nikomaru in 2024 # TODO Change this to your site name