name: mc-publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Change file name
        run: mv ./build/libs/MineStamp-1.0-SNAPSHOT-all.jar ./build/libs/MineStamp_${{ steps.tag_version.outputs.new_tag }}.jar

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: SdV5cyLq
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-draft: false
          files: |
            ./build/libs/MineStamp_${{ steps.tag_version.outputs.new_tag }}.jar
          loaders: |
            paper
            purpur
          game-versions: |
            >=1.18.2 <=1.20.4
          game-version-filter: releases
          java: |
            17
